Analyses queries
eastgenomics/Ploutos pull request #10
Opened 2022-08-03 14:06 UTC by RSWilson1

### Pull Request
This pull request add fully functioning pages for plots of compute and user costs.

**Main changes:**
- Fixed query code to function better.
- Added daily compute cost plots using highcharts allowing zoom
- Added monthly compute cost plots using highcharts
- Added daily compute cost plots by user using highcharts allowing zoom
- Added monthly compute cost plots by user using highcharts
- Added tables for each plot with the underlying data for the graph, with search and export functions.
- Fixed problem with monthly plots showing data for the wrong month.
- Monthly range available for each plot.

**Examples of plots:**

Daily
Project Plot
![image](https://user-images.githubusercontent.com/30113563/182604796-3b0be846-1f8a-43b9-b0e1-345c417fe868.png)

Assay Plot
![image](https://user-images.githubusercontent.com/30113563/182604924-b8bf5f6f-6b02-4661-94f0-ff7ee0e45bae.png)

Project and Assay plots:
![image](https://user-images.githubusercontent.com/30113563/182604862-0d89c8bd-e8de-40ed-8911-6f25e73bd19c.png)

Monthly
Project Plot
![image](https://user-images.githubusercontent.com/30113563/182604336-455848b8-7361-423e-9e00-6c8d58a996b3.png)

Assay plot
![image](https://user-images.githubusercontent.com/30113563/182603992-792615fa-7507-4c20-ac6a-75a72c172f80.png)

Project/Assay Plot
![image](https://user-images.githubusercontent.com/30113563/182604619-2956b7c1-367c-48a1-8e5c-c99b95e9a441.png)

User plots

User subset
![image](https://user-images.githubusercontent.com/30113563/182605070-3e92924d-0dca-416c-bca6-4899be9d5d04.png)

2022-08-03 14:06 UTC, pep8speaks commented
Hello @RSWilson1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`Ploutos/dashboard/forms.py`](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py):

> [Line 99:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L99): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 118:20](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L118): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 122:14](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L122): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 123:13](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L123): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 124:15](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L124): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 153:5](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L153): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 178:9](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L178): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 197:1](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L197): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 308:25](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L308): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent
> [Line 320:9](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L320): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 357:1](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L357): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 464:9](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L464): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 473:9](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L473): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 508:1](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L508): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 631:9](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/forms.py#L631): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented



* In the file [`Ploutos/dashboard/views.py`](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py):

> [Line 235:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L235): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 238:5](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L238): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 295:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L295): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 315:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L315): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 334:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L334): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 351:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L351): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 367:43](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L367): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 375:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L375): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 395:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L395): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 414:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L414): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 440:9](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L440): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 444:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L444): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)
> [Line 483:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L483): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 497:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L497): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 501:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L501): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 514:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L514): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 518:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L518): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 532:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L532): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 548:80](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L548): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 559:43](https://github.com/eastgenomics/Ploutos/blob/1d0d61dc853fdd68c489523567930a19bf700579/Ploutos/dashboard/views.py#L559): [E231](h [...]

2022-08-03 17:33 UTC, jethror1 requested changes
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 1 of 12 files reviewed, 63 unresolved discussions (waiting on @rklocke and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 113 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZRLgxEw-ks1dCtSU9:-N8ZRLgxEw-ks1dCtSUA:blryyo8) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L113)):*
> ```Python
>     converted_entries = [
>         calendar.month_name[
>             int(entry.split("-")[1])
> ```

  f string goodness here:

`f'{int(entry.split("-")[1])} {int(entry.split("-")[0])}'`

also are the `int()` calls needed?



_Code quote:_
```Python
            int(entry.split("-")[1])
        ]+" "+(entry.split("-")[0])
```
___
*[`Ploutos/dashboard/forms.py` line 299 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZSHr0AyZK4mf1XFMF:-N8ZSHr0AyZK4mf1XFMG:b7xenys) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L299)):*
> ```Python
> 
>     months_and_years = []
>     months_years_present = DailyOrgRunningTotal.objects.annotate(
> ```

comment for why we do this please
___
*[`Ploutos/dashboard/forms.py` line 306 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZSU43D0mU0MrHFRec:-N8ZSU43D0mU0MrHFRed:b-6szzd5) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L306)):*
> ```Python
>     ).distinct()
> 
>     for month_years in months_years_present:
> ```

generating this `months_and_years` list can be done in one:

```
months_and_years = [
    f"{x.get('month')}-0{x.get('year')}" for x in months_years_present
]

```

and a comment why its being done pls
___
*[`Ploutos/dashboard/forms.py` line 321 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZTFj995yUQa3VwfKg:-N8ZTFj995yUQa3VwfKh:b-f8ayg0) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L321)):*
> ```Python
>     months_and_years = ['---'] + months_and_years
> 
>     MONTH_YEAR_CHOICES = (
> ```

capitalised variables in Python tend to be reserved for globals/constants (although not real constants since they're still mutable), any reason to not be lower case?
___
*[`Ploutos/dashboard/forms.py` line 354 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZT_UcC69uHgE_Onhi:-N8ZT_UcC69uHgE_Onhj:beklcn5) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L354)):*
> ```Python
> 
>     # Append as month-year to a list
>     for month_years in months_years_present:
> ```

same as above for list comp if you're feeling fancy
___
*[`Ploutos/dashboard/forms.py` line 363 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZSEb--47uja29deQ5:-N8ZSEb--47uja29deQ6:b3x9alj) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L363)):*
> ```Python
>     converted_entries = [
>         calendar.month_name[
>             int(entry.split("-")[1])
> ```

f string here also
___
*[`Ploutos/dashboard/forms.py` line 425 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZTo_B-eUbpYiCw8oR:-N8ZTo_B-eUbpYiCw8oS:buzc58k) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L425)):*
> ```Python
>     def clean(self):
>         project_type = self.cleaned_data["project_type"]
>         assay_type = self.cleaned_data["assay_type"]
> ```

unused?



_Code quote:_
```Python
        project_type = self.cleaned_data["project_type"]
        assay_type = self.cleaned_data["assay_type"]
```
___
*[`Ploutos/dashboard/forms.py` line 476 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZTyjf9s26VQERODn_:-N8ZTyjf9s26VQERODna:b-67n6zj) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L476)):*
> ```Python
> 
> class LeaderboardForm(forms.Form):
>     """Proj type, assay type and monthyear to-from for the Compute costs"""
> ```

docstring not correct
___
*[`Ploutos/dashboard/forms.py` line 478 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZU0pE2uXeGT0PzBjY:-N8ZU0pE2uXeGT0PzBjZ:bgqar4x) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L478)):*
> ```Python
>     """Proj type, assay type and monthyear to-from for the Compute costs"""
> 
>     TYPE_CHOICES = (
> ```

should these be in a config? iirc becky uses something similar and it might be in a config
___
*[`Ploutos/dashboard/forms.py` line 505 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZUALa4Y9m8rKgXHKE:-N8ZUALa4Y9m8rKgXHKF:b-wizpgc) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L505)):*
> ```Python
>     ).distinct()
> 
>     # Append as month-year to a list
> ```

fancy list comp here too if you want (this is getting to the point of being its own simple function if you're going to do it more)
___
*[`Ploutos/dashboard/forms.py` line 514 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZUPMcD6V3l6hHwKEU:-N8ZUPMcD6V3l6hHwKEV:b-fqc2vr) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L514)):*
> ```Python
>     # Convert to format month year e.g "2022-05" -> "May 2022"
>     converted_entries = [
>         calendar.month_name[
> ```

same as somewhere above with f string magic
___
*[`Ploutos/dashboard/forms.py` line 584 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZUXqm2hSgPuktcI7e:-N8ZUXqm2hSgPuktcI7f:b-58so6z) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L584)):*
> ```Python
>         # if project_type and user_type:
>         #     if (project_type.find(",") != -1) or (user_type.find(",") != -1):
>         #         raise ValidationError(
> ```

needed?



_Code quote:_
```Python
        # Check whether >1 entries are in both proj and assay type by comma
        # if project_type and user_type:
        #     if (project_type.find(",") != -1) or (user_type.find(",") != -1):
        #         raise ValidationError(
        #             """If using both project type and assay type filters,
        #                please only enter one of each"""
        #         )
```
___
*[`Ploutos/dashboard/views.py` line 636 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZUzMA97e-0Orf6xWu:-N8ZUzMB0qO_THXmXDdz:bsi6ysw) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/views.py#L636)):*
> ```Python
>     }
>     if 'Reset' in request.GET:
>         # If nothing is submitted on the form (normal landing page)
> ```

why would reset be in the request when you just go to the page?
___
*[`Ploutos/dashboard/views.py` line 647 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZV83U12eFBmy4NXVQ:-N8ZV83U12eFBmy4NXVR:b-7gzxtt) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/views.py#L647)):*
> ```Python
>     # If the user has submitted the form
>     elif 'Daily' in request.GET:
>         # submit = Daily graphs.
> ```

is this comment needed / correct?
___
*[`Ploutos/dashboard/views.py` line 743 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZVo7h62Txd6_2Mx3_:-N8ZVo7h62Txd6_2Mx3a:bvs6zk) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/views.py#L743)):*
> ```Python
>             # If start and  [...]

2022-08-04 08:31 UTC, rklocke requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 1 of 12 files reviewed, 66 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 9 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8bxrA-9CvKoBpCrcyI:-N8bxrA-9CvKoBpCrcyJ:b-8gfu4o) ([raw file](https://github.com/eastgenomics/ploutos/blob/dd8bf6150d14d4d8e015e9e0bba7b92298965fd6/Ploutos/dashboard/forms.py#L9)):*
> ```Python
> from django.db.models.functions import ExtractMonth, ExtractYear
> from django.core.exceptions import ValidationError
> from dashboard.models import DailyOrgRunningTotal, StorageCosts, FileTypeDate
> ```

is FileTypeDate no longer imported?
___
*[`Ploutos/dashboard/forms.py` line 113 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZRLgxEw-ks1dCtSU9:-N8buqnq35kHDbvv9F25:b-lx2yjx) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L113)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

  f string goodness here:

`f'{int(entry.split("-")[1])} {int(entry.split("-")[0])}'`

also are the `int()` calls needed?

</blockquote></details>

it looks like there are two MonthlyForm classes in forms.py - my original for running totals and yours for compute. was confused why this was different from my form code i.e. 
    converted_entries = [
        dt.datetime.strptime(entry, "%Y-%m").strftime("%b %Y")
        for entry in months_and_years
    ]
could you rename one of them pls Rob?
___
*[`Ploutos/dashboard/forms.py` line 478 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZU0pE2uXeGT0PzBjY:-N8bwfzc4OGYiJCjvUt8:b-xrdu7z) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L478)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

should these be in a config? iirc becky uses something similar and it might be in a config
</blockquote></details>

these were removed from my form because I didn't use them in the end, Rob you can remove :)
___
*[`Ploutos/dashboard/views.py` line 593 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8bx2m1C0y47veK7Q5Y:-N8bx2m28OMhOAZ876tQ:b-7ipt1s) ([raw file](https://github.com/eastgenomics/ploutos/blob/dd8bf6150d14d4d8e015e9e0bba7b92298965fd6/Ploutos/dashboard/views.py#L593)):*
> ```Python
>         ).file_types_count_all_projects(date_to_filter)
> 
>     else:
> ```

where did the else go? :( 
___
*[`Ploutos/dashboard/views.py` line 635 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8bxFq9BziY2vIhwhah:-N8bxFq9BziY2vIhwhai:bxbbbem) ([raw file](https://github.com/eastgenomics/ploutos/blob/2a0e55b035ed98a105c6ebfc55a1e0655162770d/Ploutos/dashboard/views.py#L635)):*
> ```Python
>         'form': ""
>     }
>     if 'Reset' in request.GET:
> ```

I changed all of mine to request.POST and the form in the html to POST so that everything submitted and the CSRF token wasn't shown in the URL, up to you if you wanted to change as well


<!-- Sent from Reviewable.io -->

2022-08-04 08:48 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 1 of 12 files reviewed, 76 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`Ploutos/scripts/leaderboard_plots.py` line 2 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZlF9T7bThgjAYZlMU:-N8bvdwq4llnOdRyb6Mt:bk9j9j8) ([raw file](https://github.com/eastgenomics/ploutos/blob/2a0e55b035ed98a105c6ebfc55a1e0655162770d/Ploutos/scripts/leaderboard_plots.py#L2)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

up to here, this is for tomorrow me to continue as my eyes hurt
</blockquote></details>

tomorrow me is starting again
___
*[`Ploutos/scripts/leaderboard_plots.py` line 287 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8bw46V42hIco43kJV8:-N8bw46V42hIco43kJV9:b284bhx) ([raw file](https://github.com/eastgenomics/ploutos/blob/2a0e55b035ed98a105c6ebfc55a1e0655162770d/Ploutos/scripts/leaderboard_plots.py#L287)):*
> ```Python
>         Returns
>         -------
>         string.strip(',').replace(' ', '').split(',') : list
> ```

I'd just remove this and have the return be a type where it isn't an explicit variable, i.e.

```
Returns
 -------
list
    list stripped of whitespace +......
```



_Code quote:_
```Python
string.strip(',').replace(' ', '').split(',')
```
___
*[`Ploutos/scripts/leaderboard_plots.py` line 322 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8bwyti7G38H63WLk0T:-N8bwyti7G38H63WLk0U:b-u4lror) ([raw file](https://github.com/eastgenomics/ploutos/blob/2a0e55b035ed98a105c6ebfc55a1e0655162770d/Ploutos/scripts/leaderboard_plots.py#L322)):*
> ```Python
>             >> ['May 2022', 'June 2022']
>         """
>         months = [(str(
> ```

formatting here is odd, maybe something like:

```
months = [
        (
            str(entry.get('date__date__month')),
            str(entry.get('date__date__year'))
        )
        for entry in cost_list
    ]
```

or

```
months = [
        (str(entry.get('date__date__month')), str(entry.get('date__date__year')))
        for entry in cost_list
    ]
```

although line length on the 2nd might be too long, I think it makes it clearer that you're making a list of tuples



_Code quote:_
```Python
        months = [(str(
            entry.get('date__date__month')), str(entry.get('date__date__year')
                                                 )
        ) for entry in cost_list
        ]
```
___
*[`Ploutos/scripts/leaderboard_plots.py` line 328 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8bxR8Y4i-C-mKtwToe:-N8bxR8Y4i-C-mKtwTof:bg8tzh0) ([raw file](https://github.com/eastgenomics/ploutos/blob/2a0e55b035ed98a105c6ebfc55a1e0655162770d/Ploutos/scripts/leaderboard_plots.py#L328)):*
> ```Python
>         ]
> 
>         converted_months = [(self.months_in_year[int(month_year[0])-1],
> ```

again consider something like this:
```
converted_months = [
        (self.months_in_year[int(month_year[0])-1], month_year[1])
        for month_year in months
    ]
```

when you have a long list comp, keeping the part formatting/processing the individual variable to one line then the continuing for statement on a separate line can be easier to read



_Code quote:_
```Python
        converted_months = [(self.months_in_year[int(month_year[0])-1],
                             month_year[1]) for month_year in months]
```
___
*[`Ploutos/scripts/leaderboard_plots.py` line 337 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8by0JZ-sReodclb1Od:-N8by0JZ-sReodclb1Oe:bb0wqp0) ([raw file](https://github.com/eastgenomics/ploutos/blob/2a0e55b035ed98a105c6ebfc55a1e0655162770d/Ploutos/scripts/leaderboard_plots.py#L337)):*
> ```Python
>     def get_month_years_as_num_str(self, cost_list):
>         """
>         Converts a list of month years to stringified month-years
> ```

same docstring as above?



_Code quote:_
```Python
Converts a list of month years to stringified month-years
```
___
*[`Ploutos/scripts/leaderboard_plots.py` line 363 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8bxnIL4xZcEsfqBeVH:-N8bxnIL4xZcEsfqBeVI:b-jrpg2j) ([raw file](https://github.com/eastgenomics/ploutos/blob/2a0e55b035ed98a105c6ebfc55a1e0655162770d/Ploutos/scripts/leaderboard_plots.py#L363)):*
> ```Python
>         months = [(str(
>             entry.get('date__date__month')), str(entry.get('date__date__year')
>                                                  )
> ```

formatting as above



_Code quote:_
```Python
        months = [(str(
            entry.get('date__date__month')), str(entry.get('date__date__year')
                                                 )
        ) for entry in cost_list
        ]
```
___
*[`Ploutos/scripts/leaderboard_plots.py` line 373 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8bxs1d8zNBaY8KUG08:-N8bxs1d8zNBaY8KUG09:bmwklm9) ([raw file](https://github.com/eastgenomics/ploutos/blob/2a0e55b035ed98a105c6ebfc55a1e0655162770d/Ploutos/scripts/leaderboard_plots.py#L373)):*
> ```Python
>     def get_users_as_str(self, Queryset):
>         """
>         Converts a list of month years to stringified month-years
> ```

docstring wrong



_Code quote:_
```Python
Converts a list of month years to stringified month-years
```
___
*[`Ploutos/scripts/leaderboard_plots.py` line 435 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8byZpC4lTdC3LkaOkR:-N8byZpC4lTdC3LkaOkS:b5e927m) ([raw file](https://github.com/eastgenomics/ploutos/blob/2a0e55b035ed98a105c6ebfc55a1e0655162770d/Ploutos/scripts/leaderboard_plots.py#L435)):*
> ```Python
>         # Set y-axis and plot size for each project type
>         for index, project in enumerate(project_types):
>             if len(project_types) == 1:
> ```

instead of repeating yourself for each  condition you'd be better mapping these in a dict and then accessing them, something like this should work

```
project_to_plot_config = {
    1: {
        "percentage": 100,
        "height": 600
    },
    2: {
       "percentage": 50,
        "height": 800
    },
    3: {
       "percentage": 33.33,
        "height": 800
    }
}

for index, project in enumerate(project_types):
    percentage = project_to_plot_config.get(len(project_types)).get('percentage')
    height = project_to_plot_config.get(len(project_types)).get('height')

```

although I'm confused why you're looping and use the length of the list to set things since you don't use the project variable? is it just to generate a list the length of the total number of projects? If so could this whole block not just be:

```
project_to_plot_config = {
    1: {
        "percentage": 100,
        "height": 600
    },
    2: {
       "percentage": 50,
        "height": 800
    },
    3: {
       "percentage": 33.33,
        "height": 800
    }
}


percentage = project_to_plot_config.get(len(project_types)).get('percentage')
height = project_to_plot_config.get(len(project_types)).get('height')

                
y_axis_dict = {
    'title': {
        'text': f'{project} Compute Costs ($)'
    },
    'height': f'{percentage}%',
    'offset': 0,
    'lineWidth': 2
}

list_of_axis = [y_axis_dict] * len(project_types)
```
___
*[`Ploutos/scripts/leaderboard_plots.py` line 599 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8c0NrOBKPQZ2lzpAs4:-N8c0NrOBKPQZ2lzpAs5:b-3mqrf7) ([raw file](https://github.com/eastgenomics/ploutos/blob/2a0e55b035ed98a105c6ebfc55a1e0655162770d/Ploutos/scripts/leaderboard_plots.py#L599)):*
no need to loop: `users_list.extend(users)`

```
>>> l=[]
>>> s=(1,2,3)
>>> l.extend(s)
>>> l
[1, 2, 3]
```



_Code quote:_
```Python
            users = set(self.get_users_as_str(userTotals_initial))
            for user in users:
                users_list.append(user)
```
___
*[`Ploutos/scripts/leaderboard_plots.py` line 607 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8c15t5EoMwBr8rGxPg:-N8c15t6BQMqzlIEIMR9:b-gvnvm4) ([raw file](https://github.com/eastgenomic [...]

2022-08-04 09:02 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 1 of 12 files reviewed, 76 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 9 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8bxrA-9CvKoBpCrcyI:-N8c0QnuETS3mDwWKwRN:bmbfuzo) ([raw file](https://github.com/eastgenomics/ploutos/blob/dd8bf6150d14d4d8e015e9e0bba7b92298965fd6/Ploutos/dashboard/forms.py#L9)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

is FileTypeDate no longer imported?
</blockquote></details>

Yep, I have added it back now
___
*[`Ploutos/dashboard/forms.py` line 113 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZRLgxEw-ks1dCtSU9:-N8c1B2I4COj5vZbYLz5:buyvqi5) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L113)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

it looks like there are two MonthlyForm classes in forms.py - my original for running totals and yours for compute. was confused why this was different from my form code i.e. 
    converted_entries = [
        dt.datetime.strptime(entry, "%Y-%m").strftime("%b %Y")
        for entry in months_and_years
    ]
could you rename one of them pls Rob?
</blockquote></details>

Removed the extra monthly form, it was duplicated during merging conflicts.
___
*[`Ploutos/dashboard/views.py` line 593 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8bx2m1C0y47veK7Q5Y:-N8c3cYM0oFLDSOcXsV7:b-ksxo4f) ([raw file](https://github.com/eastgenomics/ploutos/blob/dd8bf6150d14d4d8e015e9e0bba7b92298965fd6/Ploutos/dashboard/views.py#L593)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

where did the else go? :( 
</blockquote></details>

yeah sorry about that the merge conflicts formatted weirdly so must have lost it during that. My bad! I will replace with your latest commit on dev branch.
___
*[`Ploutos/Ploutos/settings.py` line 154 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZXjUN1ys42yWe3RM4:-N8bqnqd-YkAL9bP4tPg:b-3rkad5) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/Ploutos/settings.py#L154)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is it?
</blockquote></details>

just checked and it is needed
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 1273 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZawRu56Et_e2gRdvx:-N8brjkk55iWppr2Xh6F:b-q68rtx) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/scripts/DNAnexus_queries.py#L1273)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this could be simplified to `if item.get('newState') in ['done', 'failed', 'terminated']:`
```
>>> l=['a', 'b', 'c']
>>> 'a' in l
True

```
</blockquote></details>

Ooh that is way more elegant! Thanks!


<!-- Sent from Reviewable.io -->

2022-08-04 09:17 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 1 of 12 files reviewed, 77 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

___
*[`Ploutos/scripts/executions_plots.py` line 697 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8c8Ir14arIX-ysPfoV:-N8c8Ir14arIX-ysPfoW:b-k3brbb) ([raw file](https://github.com/eastgenomics/ploutos/blob/59c364005f888fa15133f6ef0e96b7cb725bc3bf/Ploutos/scripts/executions_plots.py#L697)):*
> ```Python
>         all_string_months = self.get_month_years_as_num_str(initial_cost_list)
>         list_months = []
>         for month_year in all_string_months:
> ```

list comp as before



_Code quote:_
```Python
        list_months = []
        for month_year in all_string_months:
            month = month_year.split(" ")[0]
            year = month_year.split(" ")[1]
            list_months.append([month, year])
```


<!-- Sent from Reviewable.io -->

2022-08-08 15:00 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 1 of 13 files reviewed, 76 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 299 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZSHr0AyZK4mf1XFMF:-N8hdP1H1WQ8CatPA2QT:bb7f2mf) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L299)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

comment for why we do this please
</blockquote></details>

done
___
*[`Ploutos/dashboard/forms.py` line 306 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZSU43D0mU0MrHFRec:-N8hctZS2z7mYskDwJWI:bu8wsek) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L306)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

generating this `months_and_years` list can be done in one:

```
months_and_years = [
    f"{x.get('month')}-0{x.get('year')}" for x in months_years_present
]

```

and a comment why its being done pls
</blockquote></details>

changed to list comp and added if else to fix formatting. @rklocke is it okay I have changed this for your forms?
___
*[`Ploutos/dashboard/forms.py` line 321 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZTFj995yUQa3VwfKg:-N8hdcTX48to3xpCOq9K:b4nyji9) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L321)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

capitalised variables in Python tend to be reserved for globals/constants (although not real constants since they're still mutable), any reason to not be lower case?
</blockquote></details>

No reason, I have changed Becky's to lowercase too
___
*[`Ploutos/dashboard/forms.py` line 354 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZT_UcC69uHgE_Onhi:-N8heFxg4XK0ji3cZWfb:bb7f2mf) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L354)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

same as above for list comp if you're feeling fancy
</blockquote></details>

done
___
*[`Ploutos/dashboard/forms.py` line 363 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZSEb--47uja29deQ5:-N8wiBRHEJ2zvVmV-V1g:b-5j3ue) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L363)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

f string here also
</blockquote></details>

changed function no longer needed.



_Code quote:_
```Python
# Convert to format month year e.g "2022-05" -> "May 2022"
```
___
*[`Ploutos/dashboard/forms.py` line 425 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZTo_B-eUbpYiCw8oR:-N8hee-fDG7D09TIDjYO:b-4zqdff) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L425)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

unused?
</blockquote></details>

yep legacy code, removed.
___
*[`Ploutos/dashboard/forms.py` line 476 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZTyjf9s26VQERODn_:-N8wiEzw-PMPu88vyior:bvnrpcm) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L476)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

docstring not correct
</blockquote></details>

updated
___
*[`Ploutos/dashboard/forms.py` line 478 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZU0pE2uXeGT0PzBjY:-N8heiO369RQhLu_53R0:bf6j1yv) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L478)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

these were removed from my form because I didn't use them in the end, Rob you can remove :)
</blockquote></details>

yep thought I had removed them, all gone now :)
___
*[`Ploutos/dashboard/forms.py` line 505 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZUALa4Y9m8rKgXHKE:-N8wjPUuC90ZigX1SmVO:b-meeoxu) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L505)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

fancy list comp here too if you want (this is getting to the point of being its own simple function if you're going to do it more)
</blockquote></details>

I made a function for it, @rklocke do you want to have this added to your forms?



_Code quote:_
```Python
for month_years in months_years_present:
```
___
*[`Ploutos/dashboard/forms.py` line 514 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZUPMcD6V3l6hHwKEU:-N8hlBU63wDoYQmJtvQp:b7uzm2d) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L514)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

same as somewhere above with f string magic
</blockquote></details>

changed to simpler method
___
*[`Ploutos/dashboard/forms.py` line 584 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZUXqm2hSgPuktcI7e:-N8hlIjFDpkLHVWtwHEw:b8utuc0) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L584)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

needed?
</blockquote></details>

legacy, removed.
___
*[`Ploutos/dashboard/views.py` line 636 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZUzMA97e-0Orf6xWu:-N8hm8FqAWC1Mzspk9UK:bcfl1f) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/views.py#L636)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why would reset be in the request when you just go to the page?
</blockquote></details>

This comment is wrong, changed.
___
*[`Ploutos/dashboard/views.py` line 647 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZV83U12eFBmy4NXVQ:-N8hmJJf-Plk06SK0B2N:b8t5u3j) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/views.py#L647)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is this comment needed / correct?
</blockquote></details>

old comment, changed
___
*[`Ploutos/dashboard/views.py` line 743 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZVo7h62Txd6_2Mx3_:-N8hnztD4hrle1H-E9wb:b-dp8v8l) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/views.py#L743)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

do you do the same as above for plotting except get the months specified instead of 4 month default? if so, I think this setting of start and end range should be at the top, then the logic for generating plots isn't repeated (ignore me if I'm wrong, might just be my eyes :) )
</blockquote></details>

Yeah I have reformatted it to general month_start and month_end variables and that way I don't need to repeat.
___
*[`Ploutos/dashboard/views.py` line 1058 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZWfP0-hrWP1O_lTrU:-N8hq22j9uTJcEoy3AZe:bxon316) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/views.py#L1058)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is this being repeated? can it be a function?
</blockquote></detai [...]

2022-08-08 16:43 UTC, jethror1 requested changes
> Reviewed 1 of 12 files at r1, 4 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 6 of 13 files reviewed, 11 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 505 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZUALa4Y9m8rKgXHKE:-N8yI7IS7ucA-3vfzBjE:b-v2x62) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L505)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

I made a function for it, @rklocke do you want to have this added to your forms?
</blockquote></details>

can you point me to it? reviewable formatting is having fun with some many changes
___
*[`Ploutos/scripts/executions_plots.py` line 702 at r7](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8yK7sqEz3ybWkFZj7b:-N8yK7sqEz3ybWkFZj7c:b-cyvl4b) ([raw file](https://github.com/eastgenomics/ploutos/blob/9b5a4032175ee953a54dbb46c7f9d23faa8e3ed2/Ploutos/scripts/executions_plots.py#L702)):*
> ```Python
>         return json_chart_data, chart_html
> 
>     def monthly_filter_byproject(self, month_start,
> ```

are these functions now redundant with the one above?


<!-- Sent from Reviewable.io -->

2022-08-09 07:54 UTC, rklocke approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 6 of 13 files reviewed, 9 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 306 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZSU43D0mU0MrHFRec:-N90Z-S_DLsfz-HFOcjb:b-owf4bn) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L306)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

changed to list comp and added if else to fix formatting. @rklocke is it okay I have changed this for your forms?
</blockquote></details>

yes, thank you v much!
___
*[`Ploutos/dashboard/forms.py` line 505 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZUALa4Y9m8rKgXHKE:-N90ZAXL9nRJiYyPf66a:b9vp61g) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L505)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you point me to it? reviewable formatting is having fun with some many changes
</blockquote></details>

yes please, thank you!
___
*[`Ploutos/dashboard/views.py` line 635 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8bxFq9BziY2vIhwhah:-N90Zals2TqbyncxuoIK:bjsoquc) ([raw file](https://github.com/eastgenomics/ploutos/blob/2a0e55b035ed98a105c6ebfc55a1e0655162770d/Ploutos/dashboard/views.py#L635)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Ooh I will look at that, is it just changing request.GET to request.POST?
</blockquote></details>

yes so it would be like below and then changing the form method in the relevant template :) 



_Code snippet (i):_
```Python
elif 'Daily' in request.POST:
    form = ComputeForm(request.POST)
```



_Code snippet (ii):_
```Python
form method='POST'
```


<!-- Sent from Reviewable.io -->

2022-08-09 08:30 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 6 of 13 files reviewed, 10 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 62 at r7](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N90hrrf1fnW5SjB_xDR:-N90hrrf1fnW5SjB_xDS:bqlv7xt) ([raw file](https://github.com/eastgenomics/ploutos/blob/9b5a4032175ee953a54dbb46c7f9d23faa8e3ed2/Ploutos/dashboard/forms.py#L62)):*
> ```Python
>     )
> 
>     return month_year_choices, month_year_choices_2
> ```

This is the function for generating the month_year choices. Is it okay that it is in forms or should I have it elsewhere and import it?



_Code quote:_
```Python
def months_and_years(months_years_present_query):
    """
    This function takes a queryset and extracts the month years present,
    it then converts this to a list of choices for a dropdown menu.

    Args:
        months_years_present_query (queryset): queryset filtered and ordered.

    Returns:
        month_year_choices: list
            list of months formatted as "May 2022"
        month_year_choices_2: list
            list of months formatted as "May 2022"
    """
    # Append as month-year to a list
    # This allows for conversion to "month_name year" format

    months_and_years_list = [
        f"{x.get('year')}-0{x.get('month')}"
        if x.get('month') < 10
        else f"{x.get('year')}-{x.get('month')}" for x in months_years_present_query
    ]

    # Convert to format month year e.g "2022-05" -> "May 2022"
    converted_entries = [
        dt.datetime.strptime(entry, "%Y-%m").strftime("%b %Y")
        for entry in months_and_years_list
    ]

    # Add in option of blank as choice
    converted_entries = ['---'] + converted_entries
    months_and_years_list = ['---'] + months_and_years_list

    # Set as tuple choices
    month_year_choices = (
        (entry, converted_entry)
        for entry, converted_entry in zip(
            months_and_years_list, converted_entries
        )
    )

    month_year_choices_2 = (
        (entry, converted_entry)
        for entry, converted_entry in zip(
            months_and_years_list, converted_entries
        )
    )

    return month_year_choices, month_year_choices_2
```
___
*[`Ploutos/scripts/executions_plots.py` line 702 at r7](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8yK7sqEz3ybWkFZj7b:-N90fyqxDuqHL0L9_Neu:b-ifhevm) ([raw file](https://github.com/eastgenomics/ploutos/blob/9b5a4032175ee953a54dbb46c7f9d23faa8e3ed2/Ploutos/scripts/executions_plots.py#L702)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

are these functions now redundant with the one above?
</blockquote></details>

Yes, removed now.


<!-- Sent from Reviewable.io -->

2022-08-09 08:39 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 2 of 13 files reviewed, 10 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

___
*[`Ploutos/dashboard/views.py` line 635 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8bxFq9BziY2vIhwhah:-N90kY80EgJg_eshhaVJ:b-ozlwkr) ([raw file](https://github.com/eastgenomics/ploutos/blob/2a0e55b035ed98a105c6ebfc55a1e0655162770d/Ploutos/dashboard/views.py#L635)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

yes so it would be like below and then changing the form method in the relevant template :) 
</blockquote></details>

Nice that was easy! Done


<!-- Sent from Reviewable.io -->

2022-08-09 08:44 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 2 of 13 files reviewed, 11 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

*[a discussion](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N90lPSAB8GiCVtVFniG:-N90lPSAB8GiCVtVFniH:b1neeun) (no related file):*
@rklocke Do you mind if I change your bar_chart.html to something like storage.html?

___


<!-- Sent from Reviewable.io -->

2022-08-09 09:05 UTC, rklocke approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 2 of 13 files reviewed, 10 unresolved discussions (waiting on @jethror1 and @RSWilson1)

*[a discussion](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N90lPSAB8GiCVtVFniG:-N90o_Bw0spXzv6YFhQL:bfj2bu5) (no related file):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

@rklocke Do you mind if I change your bar_chart.html to something like storage.html?
</blockquote></details>

yep that makes sense to me :) could you update the template name in views.py if so as well pls? thanks!

___
___
*[`Ploutos/dashboard/forms.py` line 62 at r7](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N90hrrf1fnW5SjB_xDR:-N90q-7X61ppDF8gNzzv:bpw0ozn) ([raw file](https://github.com/eastgenomics/ploutos/blob/9b5a4032175ee953a54dbb46c7f9d23faa8e3ed2/Ploutos/dashboard/forms.py#L62)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

This is the function for generating the month_year choices. Is it okay that it is in forms or should I have it elsewhere and import it?
</blockquote></details>

(not sure if you were asking me) but fine by me to stay in forms :)


<!-- Sent from Reviewable.io -->

2022-08-09 09:11 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 2 of 14 files reviewed, 9 unresolved discussions (waiting on @jethror1 and @RSWilson1)

*[a discussion](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N90lPSAB8GiCVtVFniG:-N90rnBP86YDozeBaBNO:bucjhyl) (no related file):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

yep that makes sense to me :) could you update the template name in views.py if so as well pls? thanks!
</blockquote></details>

Yep, all done!

___


<!-- Sent from Reviewable.io -->

2022-08-09 09:11 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 2 of 14 files reviewed, 9 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 62 at r7](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N90hrrf1fnW5SjB_xDR:-N90rteN0RQAvEXsdnSC:b-e0rgd9) ([raw file](https://github.com/eastgenomics/ploutos/blob/9b5a4032175ee953a54dbb46c7f9d23faa8e3ed2/Ploutos/dashboard/forms.py#L62)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

(not sure if you were asking me) but fine by me to stay in forms :)
</blockquote></details>

Yeah this was for @jethror1


<!-- Sent from Reviewable.io -->

2022-08-09 13:00 UTC, jethror1 reviewed
> Reviewed 1 of 6 files at r2, 2 of 10 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, 4 of 5 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 62 at r7](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N90hrrf1fnW5SjB_xDR:-N91Yf9f-TOshwbsGkN6:bfi2jb5) ([raw file](https://github.com/eastgenomics/ploutos/blob/9b5a4032175ee953a54dbb46c7f9d23faa8e3ed2/Ploutos/dashboard/forms.py#L62)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Yeah this was for @jethror1
</blockquote></details>

if its not being reused elsewhere then sure, if this got bigger I'd consider moving to a `utils.py` or something but its fine for now


<!-- Sent from Reviewable.io -->

2022-08-09 13:56 UTC, RSWilson1 reviewed
I think this is done

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10#-:-N91rURYACBQFUqze1Jv:b-1yvy5c)* status: 9 of 15 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 306 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZSU43D0mU0MrHFRec:-N91mq-rD-X9CYgzVNzr:bb7f2mf) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L306)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

yes, thank you v much!
</blockquote></details>

done
___
*[`Ploutos/dashboard/forms.py` line 505 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZUALa4Y9m8rKgXHKE:-N91meij6pfu5vhlLdMe:bqh2qxu) ([raw file](https://github.com/eastgenomics/ploutos/blob/828354943349bea870f67300a1e5d1558ad04e20/Ploutos/dashboard/forms.py#L505)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

yes please, thank you!
</blockquote></details>

changed to new function.
___
*[`Ploutos/dashboard/forms.py` line 62 at r7](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N90hrrf1fnW5SjB_xDR:-N91mUJJ7YtdakEiOch8:b-evp6wd) ([raw file](https://github.com/eastgenomics/ploutos/blob/9b5a4032175ee953a54dbb46c7f9d23faa8e3ed2/Ploutos/dashboard/forms.py#L62)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

if its not being reused elsewhere then sure, if this got bigger I'd consider moving to a `utils.py` or something but its fine for now
</blockquote></details>

Okay I will leave there for now as will only be using in form.py
___
*[`Ploutos/scripts/leaderboard_plots.py` line 2 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N8ZlF9T7bThgjAYZlMU:-N91mZ2W4fxwCXoPqAyJ:beya8fb) ([raw file](https://github.com/eastgenomics/ploutos/blob/2a0e55b035ed98a105c6ebfc55a1e0655162770d/Ploutos/scripts/leaderboard_plots.py#L2)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

tomorrow me is starting again
</blockquote></details>

Hope your eyes feel better!


<!-- Sent from Reviewable.io -->

2022-08-09 14:08 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: 9 of 15 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 62 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/10#-N91vgs8ANrVKjX6EgSb:-N91vgs8ANrVKjX6EgSc:bcm8hvz) ([raw file](https://github.com/eastgenomics/ploutos/blob/50cc7775300c0cc98f92f7e601c0e95a4f1bef70/Ploutos/dashboard/forms.py#L62)):*
> ```Python
>     )
> 
>     return month_year_choices, month_year_choices_2
> ```

Here's the function again @jethror1 



_Code quote:_
```Python
def months_and_years(months_years_present_query):
    """
    This function takes a queryset and extracts the month years present,
    it then converts this to a list of choices for a dropdown menu.

    Args:
        months_years_present_query (queryset): queryset filtered and ordered.

    Returns:
        month_year_choices: list
            list of months formatted as "May 2022"
        month_year_choices_2: list
            list of months formatted as "May 2022"
    """
    # Append as month-year to a list
    # This allows for conversion to "month_name year" format

    months_and_years_list = [
        f"{x.get('year')}-0{x.get('month')}"
        if x.get('month') < 10
        else f"{x.get('year')}-{x.get('month')}" for x in months_years_present_query
    ]

    # Convert to format month year e.g "2022-05" -> "May 2022"
    converted_entries = [
        dt.datetime.strptime(entry, "%Y-%m").strftime("%b %Y")
        for entry in months_and_years_list
    ]

    # Add in option of blank as choice
    converted_entries = ['---'] + converted_entries
    months_and_years_list = ['---'] + months_and_years_list

    # Set as tuple choices
    month_year_choices = (
        (entry, converted_entry)
        for entry, converted_entry in zip(
            months_and_years_list, converted_entries
        )
    )

    month_year_choices_2 = (
        (entry, converted_entry)
        for entry, converted_entry in zip(
            months_and_years_list, converted_entries
        )
    )

    return month_year_choices, month_year_choices_2
```


<!-- Sent from Reviewable.io -->

2022-08-09 15:02 UTC, jethror1 approved these changes
> Reviewed 1 of 10 files at r6, 1 of 2 files at r7, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: all files reviewed, 1 unresolved discussion (waiting on @RSWilson1)



<!-- Sent from Reviewable.io -->

2022-08-09 15:02 UTC, jethror1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10#-:-N927GEt9rfj0qBxfQsQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RSWilson1)



<!-- Sent from Reviewable.io -->

2022-08-09 15:03 UTC, jethror1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/10)* status: all files reviewed, 1 unresolved discussion (waiting on @RSWilson1)



<!-- Sent from Reviewable.io -->

2022-08-09 15:05 UTC, merged