Development
eastgenomics/Ploutos pull request #4
Opened 2022-05-27 14:09 UTC by RSWilson1

Our progress so far, after merging scripts in pair programming session.

2022-05-27 14:09 UTC, pep8speaks commented
Hello @RSWilson1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`Ploutos/Ploutos/settings.py`](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/Ploutos/settings.py):

> [Line 21:20](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/Ploutos/settings.py#L21): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 116:80](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/Ploutos/settings.py#L116): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 119:80](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/Ploutos/settings.py#L119): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 122:80](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/Ploutos/settings.py#L122): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 125:80](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/Ploutos/settings.py#L125): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

* In the file [`Ploutos/Ploutos/urls.py`](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/Ploutos/urls.py):

> [Line 24:2](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/Ploutos/urls.py#L24): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file







* In the file [`Ploutos/dashboard/forms.py`](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/forms.py):

> [Line 5:1](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/forms.py#L5): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 7:65](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/forms.py#L7): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 8:64](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/forms.py#L8): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 8:80](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/forms.py#L8): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 8:85](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/forms.py#L8): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 14:12](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/forms.py#L14): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 17:1](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/forms.py#L17): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`Ploutos/dashboard/models.py`](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/models.py):

> [Line 4:1](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/models.py#L4): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 11:1](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/models.py#L11): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 19:1](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/models.py#L19): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 29:1](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/models.py#L29): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 39:1](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/models.py#L39): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 55:1](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/models.py#L55): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 60:5](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/models.py#L60): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '





* In the file [`Ploutos/dashboard/views.py`](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py):

> [Line 7:1](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py#L7): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 9:53](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py#L9): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 20:44](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py#L20): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 20:46](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py#L20): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 20:80](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py#L20): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 79 characters)
> [Line 20:87](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py#L20): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 20:110](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py#L20): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 26:80](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py#L26): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 27:80](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py#L27): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 29:5](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py#L29): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 30:5](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py#L30): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 30:80](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py#L30): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (162 > 79 characters)
> [Line 38:11](https://github.com/eastgenomics/Ploutos/blob/b6abd9b071f09711e83b433d1b5bce737124235a/Ploutos/dashboard/views.py#L38): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around k [...]

2022-05-30 22:20 UTC, jethror1 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: 0 of 52 files reviewed, 1 unresolved discussion (waiting on @rklocke and @RSWilson1)

___
*[`.gitignore` line 3 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M2WBkEqHsTIb0RBOL:-N3M2WBkEqHsTIb0RBOM:b-c30e1k) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/.gitignore#L3)):*
> ```ignore
> *.csv
> *.csv#
> *.pyc
> ```

change this like your migrations to exlcude `.pyc` from all dirs


<!-- Sent from Reviewable.io -->

2022-05-30 22:27 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: 0 of 52 files reviewed, 3 unresolved discussions (waiting on @rklocke and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 11 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M3DxF2dUin2zcZi7s:-N3M3DxF2dUin2zcZi7t:b-sgzo2l) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/dashboard/forms.py#L11)):*
> ```Python
> 
>     def clean_end(self):
>         """docstring"""
> ```

complete docstring, examples if it helps: https://github.com/eastgenomics/eggd_generate_workbook/blob/master/resources/home/dnanexus/generate_workbook/utils/columns.py
___
*[`Ploutos/dashboard/views.py` line 20 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M48-T6DGbwLRdPvIZ:-N3M48-T6DGbwLRdPvI_:ba35xbx) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/dashboard/views.py#L20)):*
> ```Python
>     # Filter totals based on the dates provided in start and end (foreign key)
>     if start:
>         totals = totals.filter(date__id__in = (Dates.objects.filter(date__range=[start,end]).values_list('id',flat=True)))
> ```

line is pretty long for pep8


<!-- Sent from Reviewable.io -->

2022-05-30 22:35 UTC, jethror1 requested changes
> Reviewed 3 of 23 files at r1, 1 of 32 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: 4 of 52 files reviewed, 6 unresolved discussions (waiting on @rklocke and @RSWilson1)

___
*[`Ploutos/Ploutos/settings.py` line 26 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M4_Q6A_ag6aSqMw7O:-N3M4_Q6A_ag6aSqMw7P:b-hbn6di) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/Ploutos/settings.py#L26)):*
> ```Python
> 
> # Assign keys to data from the file
> DB_USERNAME = CREDENTIALS['DB_USERNAME']
> ```

I'd consider using `.get()` instead of selecting by key from a dict as it is better for error handling, and allows you to have defaults. 

i.e. you could have the `LIVE_STORAGE_COST_MONTH` have a default with `CREDENTIALS.get('LIVE_STORAGE_COST_MONTH', {default})`
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 32 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M5PXc-zjZD63dE_zq:-N3M5PXc-zjZD63dE_zr:bzgc80p) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L32)):*
> ```Python
>             authorisation token for DNAnexus, from settings.py
> 
>         Returns
> ```

Adding what a function may raise and why to docstrings may be useful, example: https://github.com/eastgenomics/eggd_generate_workbook/blob/208a2c01962d8894426edd5c2f2a4dc8b634ace8/resources/home/dnanexus/generate_workbook/utils/columns.py#L85
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 47 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M5_pf4Hq4V6m5ydBG:-N3M5_pf4Hq4V6m5ydBH:b-x6601s) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L47)):*
> ```Python
>         dx.api.system_whoami()
>         print("DNAnexus login successful")
>     except:
> ```

better to catch the exception and handle show it, i.e.

```
except Exception as e:
    print(f'Error in logging in to DNAnexus: {e}')
```


<!-- Sent from Reviewable.io -->

2022-05-30 22:36 UTC, jethror1 reviewed
> Reviewed 5 of 23 files at r1, 2 of 32 files at r6, 2 of 20 files at r9.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: 13 of 52 files reviewed, 6 unresolved discussions (waiting on @rklocke and @RSWilson1)



<!-- Sent from Reviewable.io -->

2022-05-31 17:56 UTC, jethror1 requested changes
> Reviewed 2 of 23 files at r1, 2 of 32 files at r3, 5 of 28 files at r5, 8 of 32 files at r6, 14 of 20 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: 46 of 52 files reviewed, 35 unresolved discussions (waiting on @rklocke and @RSWilson1)

___
*[`Ploutos/dashboard/models.py` line 31 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q-5c_DKclb9mxNNoh:-N3Q-5c_DKclb9mxNNoi:bkd2ql5) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/dashboard/models.py#L31)):*
> ```Python
> class DailyOrgRunningTotal(models.Model):
>     """Model representing running totals for the org"""
>     date = models.ForeignKey(Dates, on_delete=models.CASCADE, unique=True)
> ```

be careful using `CASCADE`, is it what you want to do?
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 71 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q3PWY4H8OfajcBIW_:-N3Q3PWY4H8OfajcBIWa:b-67yt5s) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L71)):*
> ```Python
>     """
>     project_response = list(dx.find_projects(
>         billed_to=settings.ORG, level='VIEW', describe=True))
> ```

can you limit the describe return or is it not worth it for what is returned?
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 87 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q3kVz0wxntaZiJ56o:-N3Q3kVz0wxntaZiJ56p:b-e4iq2t) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L87)):*
> ```Python
>         list_projects_dicts.append(item)
> 
>     # Create a df with a row for each project from the dict
> ```

it can sometimes be easier to read if you don't have alternating lines of code and comments (or maybe its just me), something like:

```
# create df of project data, one project per row, keep only required columns
projects_df = pd.DataFrame(list_projects_dicts)
projects_df = projects_df.drop(columns=['name', 'created_by', 'created'])
projects_df.columns = ['project', 'created_epoch']
```

or ignore me, also fine :smiley: 

Also as an aside there is a [rename](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html) method for pandas, more useful when you have more than  2 columns
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 99 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q50wSBYMJo1fu12P7:-N3Q50wSBYMJo1fu12P8:b-hs9p3z) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L99)):*
> ```Python
> def get_files(proj):
>     """
>     Get all files for the project in DNAnexus, storing each file and its size, name and archival state. 
> ```

white space at end of line
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 104 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q58GfBcMOGuR2hiN4:-N3Q58GgEIUuyo7RDV-j:b-2mpcw6) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L104)):*
> ```Python
>     Parameters
>     ----------
>     proj : entry in list
> ```

entry in list? if you're being consistent with other docstrings consider something like:
```
proj : str
    given project to retrieve all files for
```
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 109 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q5Q09-C1EiBRsXTiX:-N3Q5Q09-C1EiBRsXTiY:b2kgsh2) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L109)):*
> ```Python
>     -------
>      project_files_dict : collections.defaultdict
>         dictionary with all the files per project
> ```

files and metadata



_Code quote:_
```Python
files
```
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 119 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q5nsh5PHfEPtHb1-J:-N3Q5nsh5PHfEPtHb1-K:b-sjwapu) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L119)):*
> ```Python
>     files = list(dx.search.find_data_objects(classname='file', project=proj,
>                                              describe={
>                                                  'fields': {'archivalState': True, 'size': True, 'name': True}
> ```

this is quite long and goes against pep8 indentation, consider something like:
```
files = list(dx.search.find_data_objects(
    classname='file', project=proj,
    describe={'fields': {'archivalState': True, 'size': True, 'name': True}}
))
```

or

```
files = list(dx.search.find_data_objects(
    classname='file', project=proj,
    describe={'fields': {
        'archivalState': True,
        'size': True,
        'name': True
    }}
))
```
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 121 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q6azF5_igPQuwuU6R:-N3Q6azF5_igPQuwuU6S:biaak6m) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L121)):*
> ```Python
>                                                  'fields': {'archivalState': True, 'size': True, 'name': True}
>                                              }))
>     for file in files:
> ```

formatting:

```
for file in files:
    proj = file['project']
    project_files_dict[proj]["files"].append({
        "id": file["id"],
        "name": file["describe"]['name'],
        "size": file.get('describe', {}).get('size', 0),
        "state": file['describe']['archivalState']
    })
```
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 131 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q6l694aWD8AjbJTY_:-N3Q6l694aWD8AjbJTYa:b-ba33p8) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L131)):*
> ```Python
> 
> 
> def threadify(project_list, get_files_function):
> ```

excellent naming, 10/10
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 133 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q6r3Y5ULZfbH5uNIu:-N3Q6r3Y5ULZfbH5uNIv:b-bi26fw) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L133)):*
> ```Python
> def threadify(project_list, get_files_function):
>     """
>     Use ThreadPoolExecutor on get_files() function
> ```

could you expand slightly, think more why a function is being used or describing what its returning than just what it does as this should be (usually) easy to understand from reading the code
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 139 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q7D9V6eSeol0mHLdM:-N3Q7D9V6eSeol0mHLdN:bt7rvap) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L139)):*
> ```Python
>     project_list : list
>         list of all the projects in DNAnexus
>     get_files_function: function
> ```

does this need passing as an input? can you not just access it from the local namespace inside the function?
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 151 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q8jJY3W7g07BQJkxt:-N3Q8jJZ4cYS8ke4JV24:b-o72tvv) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L151)):*
> ```Python
>       [
>           {
>         'file_id': 'file-1', 'name': "IamFile1.json", 'size': 4803,
> ```

Excellent docstring, makes it really easier to pick up later if you can easily tell data structure :smiley: 

another tiny thing but formatting dicts as stacked by keys can be easier to read, again just pe [...]

2022-05-31 18:00 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: 46 of 52 files reviewed, 36 unresolved discussions (waiting on @rklocke and @RSWilson1)

___
*[`Ploutos/scripts/populate_db.py` line 5 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3QGFSH-Y7mw7YrHC6k:-N3QGFSH-Y7mw7YrHC6l:bbnpqqi) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/populate_db.py#L5)):*
> ```Python
> """
> 
> from dashboard.models import ComputeCosts, Users, Dates, Projects, Executables
> ```

consider formatting imports alphanumerically and split as std lib -> 3rd party -> local imports:

```
import a_standard
import b_standard

import a_third_party
import b_third_party

from a_soc import f
from a_soc import g
from b_soc import d
```
https://stackoverflow.com/a/20763446


<!-- Sent from Reviewable.io -->

2022-06-06 10:45 UTC, rklocke reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: 46 of 52 files reviewed, 36 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

___
*[`.gitignore` line 3 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M2WBkEqHsTIb0RBOL:-N3saMnmEiarFY67VAO3:b-ujvovx) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/.gitignore#L3)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

change this like your migrations to exlcude `.pyc` from all dirs
</blockquote></details>

As discussed and checked with a test file, *.pyc should work
___
*[`Ploutos/dashboard/models.py` line 31 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q-5c_DKclb9mxNNoh:-N3saowtD2jN7LT1693H:b-f8uf) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/dashboard/models.py#L31)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

be careful using `CASCADE`, is it what you want to do?
</blockquote></details>

As discussed, will think about what to do on_delete and decide later
___
*[`Ploutos/Ploutos/settings.py` line 26 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M4_Q6A_ag6aSqMw7O:-N3sb3yQEBuK2hkRVhq6:b-drvgt9) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/Ploutos/settings.py#L26)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I'd consider using `.get()` instead of selecting by key from a dict as it is better for error handling, and allows you to have defaults. 

i.e. you could have the `LIVE_STORAGE_COST_MONTH` have a default with `CREDENTIALS.get('LIVE_STORAGE_COST_MONTH', {default})`
</blockquote></details>

Have added .get, not included a default yet as unclear what to set these as (and setting our prices as the default is against confidentiality).


<!-- Sent from Reviewable.io -->

2022-06-06 10:52 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: 46 of 52 files reviewed, 35 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

___
*[`.gitignore` line 3 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M2WBkEqHsTIb0RBOL:-N3scYkX01NfPDzgB2-1:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/.gitignore#L3)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

As discussed and checked with a test file, *.pyc should work
</blockquote></details>

Done.
___
*[`Ploutos/dashboard/forms.py` line 11 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M3DxF2dUin2zcZi7s:-N3sc1Mp0JKXFPDyfZ-g:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/dashboard/forms.py#L11)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

complete docstring, examples if it helps: https://github.com/eastgenomics/eggd_generate_workbook/blob/master/resources/home/dnanexus/generate_workbook/utils/columns.py
</blockquote></details>

Done.
___
*[`Ploutos/dashboard/models.py` line 31 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q-5c_DKclb9mxNNoh:-N3sbwJn9tGyYdLPC4t3:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/dashboard/models.py#L31)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

As discussed, will think about what to do on_delete and decide later
</blockquote></details>

Done.
___
*[`Ploutos/dashboard/views.py` line 20 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M48-T6DGbwLRdPvIZ:-N3saDRE67KBLVz9Iqut:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/dashboard/views.py#L20)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

line is pretty long for pep8
</blockquote></details>

Done.
___
*[`Ploutos/Ploutos/settings.py` line 26 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M4_Q6A_ag6aSqMw7O:-N3sb6QQ27hY-oL33Bg2:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/Ploutos/settings.py#L26)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I'd consider using `.get()` instead of selecting by key from a dict as it is better for error handling, and allows you to have defaults. 

i.e. you could have the `LIVE_STORAGE_COST_MONTH` have a default with `CREDENTIALS.get('LIVE_STORAGE_COST_MONTH', {default})`
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 32 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M5PXc-zjZD63dE_zq:-N3sbI4s2RliKYBfLAgl:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L32)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Adding what a function may raise and why to docstrings may be useful, example: https://github.com/eastgenomics/eggd_generate_workbook/blob/208a2c01962d8894426edd5c2f2a4dc8b634ace8/resources/home/dnanexus/generate_workbook/utils/columns.py#L85
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 47 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M5_pf4Hq4V6m5ydBG:-N3sbNpp659_BuTCr0F6:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L47)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

better to catch the exception and handle show it, i.e.

```
except Exception as e:
    print(f'Error in logging in to DNAnexus: {e}')
```
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 71 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q3PWY4H8OfajcBIW_:-N3sbR5h1ziRbqucsaXa:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L71)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you limit the describe return or is it not worth it for what is returned?
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 87 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q3kVz0wxntaZiJ56o:-N3scer163rpurlbqVA6:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L87)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

it can sometimes be easier to read if you don't have alternating lines of code and comments (or maybe its just me), something like:

```
# create df of project data, one project per row, keep only required columns
projects_df = pd.DataFrame(list_projects_dicts)
projects_df = projects_df.drop(columns=['name', 'created_by', 'created'])
projects_df.columns = ['project', 'created_epoch']
```

or ignore me, also fine :smiley: 

Also as an aside there is a [rename](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html) method for pandas, more useful when you have more than  2 columns
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 99 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q50wSBYMJo1fu12P7:-N3scfbeD36-uYXgCa3e:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L99)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

white space at end of line
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 104 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q58GfBcMOGuR2hiN4:-N3scgGD96tIqyhHQ3nX:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L104)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

entry in list? if you're being consistent with other docstrings consider something like:
```
proj : str
    given project to retrieve all files for
```
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 109 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q5Q09-C1EiBRsXTiX:-N3scgfn9YluJKJw91OB:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L109)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

files and metadata
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 119 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q5nsh5PHfEPtHb1-J:-N3schLP6bKsbdsWoGuz:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L119)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this is quite long and goes against pep8 indentation, consider something like:
```
files = list(dx.search.find_data_objects(
    classname='file', project=proj,
    describe={'fields': {'archivalState': True, 'size': True, 'name': True}}
))
```

or

```
files = list(dx.search.find_data_objects(
    classname='file', project=proj,
    describe={'fields': {
        'archivalState': True,
        'size': True,
        'name': True
    }}
))
```
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 121 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q6azF5_igPQuwuU6R:-N3sciCT2ayXykDOibzT:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob [...]

2022-06-06 10:58 UTC, rklocke approved these changes
> Reviewed 3 of 6 files at r11, 1 of 1 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: all files reviewed, 35 unresolved discussions (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-06-06 10:59 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: all files reviewed, 35 unresolved discussions (waiting on @jethror1)

___
*[`Ploutos/Ploutos/settings.py` line 26 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3M4_Q6A_ag6aSqMw7O:-N3sem2XDn9CSEU6wCbd:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/Ploutos/settings.py#L26)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-06 11:03 UTC, RSWilson1 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4#-:-N3sfZGaCBujpCKO8_0G:bnfp4nl)* status: all files reviewed, 35 unresolved discussions (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-06-06 11:04 UTC, rklocke approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: all files reviewed, 35 unresolved discussions (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-06-13 14:59 UTC, RSWilson1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: 49 of 52 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @rklocke)

___
*[`Ploutos/scripts/DNAnexus_queries.py` line 139 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3Q7D9V6eSeol0mHLdM:-N4SUZG0-wbU2dDxf4AO:b-hafzls) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L139)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

`get_files_function` is no longer an input
</blockquote></details>

Yep, I have removed this from the docstring now.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 237 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3QB8WKBuALhDQaaC8R:-N4SUhAeEBRtyrgK3j_U:bg09m5t) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L237)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

the below `project = proj` isn't needed, just use `project` as the variable in the loop or change to `row['project'] = proj` below
</blockquote></details>

Changed proj to project in both functions.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 623 at r10](https://reviewable.io/reviews/eastgenomics/ploutos/4#-N3QFIao3YuBKW46Hi9b:-N4SUlhq8NVTvd0kVnCN:bg09m5t) ([raw file](https://github.com/eastgenomics/ploutos/blob/e29df79320001681ea221d5d385edebfb7c29063/Ploutos/scripts/DNAnexus_queries.py#L623)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

as before, don't use the `project = proj`
</blockquote></details>

Changed proj to project in both functions.


<!-- Sent from Reviewable.io -->

2022-06-13 15:17 UTC, jethror1 approved these changes
> Reviewed 1 of 7 files at r7, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RSWilson1)



<!-- Sent from Reviewable.io -->

2022-06-13 15:17 UTC, jethror1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RSWilson1)



<!-- Sent from Reviewable.io -->

2022-06-13 15:17 UTC, merged