Plotting
eastgenomics/Ploutos pull request #7
Opened 2022-07-21 14:54 UTC by rklocke

**Plotting into development**
Summary of main changes:
- Added monthly plotting for the Running Totals page. Users can select between specific dates for the first chart and between specific months for the second chart.
- Added file type storage page. Can now see sizes of live and archived FASTQs, BAMs and VCFs across all projects, project types (001,002 etc), assay types (CEN, TWE), combination (002*CEN) or specific project. Page also includes a 'Total size of unique files in DNAnexus today' showing both live and archived. 
- Added DataTables for easy exporting of data both from all of the charts and also on a project level for the Storage Cost page and the File Type Storage page.
- Changed the Storage Cost page to 'Start month' and 'End month' rather than all months or a specific month. This means the chart now defaults to the last four months unless a month range is specified, making it easier if multiple years are in the database.
- Added helpful text at the top of the three pages with icons.
- Switched to Django Crispy Forms (easier to arrange form fields and include help text).

![image](https://user-images.githubusercontent.com/67269227/180244895-da0fbef6-7fa0-4816-8559-4487e9b870e4.png)
![image](https://user-images.githubusercontent.com/67269227/180244922-c8445ab0-5fe5-4625-8f89-65a99dc29e8a.png)
![image](https://user-images.githubusercontent.com/67269227/180244966-4b14ae24-39fd-40c4-8d26-4002e69577d2.png)
![image](https://user-images.githubusercontent.com/67269227/180244999-fcf8fdf6-fa5c-42ea-90b3-254d883d8286.png)
![image](https://user-images.githubusercontent.com/67269227/180245037-c3c0e287-d6ce-4406-bbd6-94535d164947.png)
![image](https://user-images.githubusercontent.com/67269227/180245058-c7aff11a-bdb5-40ed-bfc8-e34adf731ea7.png)
![image](https://user-images.githubusercontent.com/67269227/180245090-5435b187-063f-4889-9009-09b140761e97.png)
![image](https://user-images.githubusercontent.com/67269227/180245148-c48cc9b9-62c9-4355-89b8-22c27f04ccd1.png)

2022-07-21 14:54 UTC, pep8speaks commented
Hello @rklocke! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`Ploutos/Ploutos/settings.py`](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/Ploutos/settings.py):

> [Line 150:1](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/Ploutos/settings.py#L150): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 164:80](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/Ploutos/settings.py#L164): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)

* In the file [`Ploutos/dashboard/forms.py`](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/forms.py):

> [Line 105:20](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/forms.py#L105): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 109:14](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/forms.py#L109): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 110:13](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/forms.py#L110): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 111:15](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/forms.py#L111): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 162:9](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/forms.py#L162): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 302:9](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/forms.py#L302): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 337:1](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/forms.py#L337): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 402:25](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/forms.py#L402): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent

* In the file [`Ploutos/dashboard/models.py`](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/models.py):

> [Line 52:1](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/models.py#L52): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 56:1](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/models.py#L56): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 64:1](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/models.py#L64): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 82:80](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/models.py#L82): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 91:28](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/models.py#L91): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file
> [Line 91:28](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/models.py#L91): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file
> [Line 91:28](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/models.py#L91): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file



* In the file [`Ploutos/dashboard/views.py`](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/views.py):

> [Line 46:13](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/views.py#L46): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 337:43](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/views.py#L337): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 404:34](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/views.py#L404): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 444:1](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/views.py#L444): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 465:17](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/dashboard/views.py#L465): [E129](https://duckduckgo.com/?q=pep8%20E129) visually indented line with same indent as next logical line

* In the file [`Ploutos/scripts/DNAnexus_queries.py`](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/scripts/DNAnexus_queries.py):

> [Line 296:5](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/scripts/DNAnexus_queries.py#L296): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 328:80](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/scripts/DNAnexus_queries.py#L328): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 425:1](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/scripts/DNAnexus_queries.py#L425): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 467:20](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/scripts/DNAnexus_queries.py#L467): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 475:29](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/scripts/DNAnexus_queries.py#L475): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 476:20](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/scripts/DNAnexus_queries.py#L476): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 488:1](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/scripts/DNAnexus_queries.py#L488): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 534:61](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/scripts/DNAnexus_queries.py#L534): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 575:1](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/scripts/DNAnexus_queries.py#L575): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 577:80](https://github.com/eastgenomics/Ploutos/blob/a66f683ad96336580c7eb0ff4e404b832cdb7cdf/Ploutos/scripts/DNAnexus_queries.py#L577): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 647:17](https://github.com/ [...]

2022-07-21 16:22 UTC, jethror1 requested changes
> Reviewed 6 of 20 files at r1, 2 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/7)* status: 7 of 21 files reviewed, 16 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 62 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WR3DA825PkV82Wpbk:-N7WR3DA825PkV82Wpbl:b-ewlt2u) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/forms.py#L62)):*
> ```Python
>         # Check both dates are entered
>         if start:
>             if not end:
> ```

since you're not doing anything if start and end are true, this can be one line:
```
if start and not end:
```



_Code quote:_
```Python
        if start:
            if not end:
```
___
*[`Ploutos/dashboard/forms.py` line 69 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WRE4f0l-R_NsqW3aV:-N7WRE4f0l-R_NsqW3aW:bnj7hl0) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/forms.py#L69)):*
> ```Python
> 
>         if end:
>             if not start:
> ```

same as above



_Code quote:_
```Python
        if end:
            if not start:
```
___
*[`Ploutos/dashboard/forms.py` line 184 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WRfhuDtWj2UDZIKLY:-N7WRfhuDtWj2UDZIKLZ:b-dtd77p) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/forms.py#L184)):*
> ```Python
>     """Proj type, assay type and monthyear to-from for the storage costs"""
> 
>     TYPE_CHOICES = (
> ```

should these be in a config?
___
*[`Ploutos/dashboard/models.py` line 75 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WSa-98DCpgcLOg_Ld:-N7WSa-98DCpgcLOg_Le:b-1dim7t) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/models.py#L75)):*
> ```Python
>     file_state = models.ForeignKey(FileTypeState, on_delete=models.CASCADE)
> 
> # class Executables(models.Model):
> ```

are these commented out from being old ones of robs? can you delete them if so to reduce conflicts on the next PR
___
*[`Ploutos/dashboard/views.py` line 68 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WTBnWD3lpkYBS68yS:-N7WTBnWD3lpkYBS68yT:b2xlu7m) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/views.py#L68)):*
> ```Python
>                 chart = fig.to_html()
> 
>                 # Send filtered chart1 and unfiltered chart 2 to context
> ```

what are chat and chart2? could these be more descriptive? if not a comment on what each are in the context of this part of the code would be useful (i.e chart is blah and chart 2 is blah)
___
*[`Ploutos/dashboard/templates/dashboard/bar_chart.html` line 5 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WVbCu2cR5g3eDp5ko:-N7WVbCu2cR5g3eDp5kp:bb97ejf) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/bar_chart.html#L5)):*
> ```HTML
> {% block content %}
> <!-- Highlights current page and removes highlighting from previous -->
> <script>
> ```

can  you move all `<script>` tags to the bottom. this will speed up loading
___
*[`Ploutos/dashboard/templates/dashboard/bar_chart.html` line 61 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WVxMC5ACGi2HBEIM-:-N7WVxMC5ACGi2HBEIM0:b-zhvv63) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/bar_chart.html#L61)):*
> ```HTML
>     $(document).ready(function () {
>     $('.dataframe').DataTable( {
>         scrollY: '75vh',
> ```

I think you want `scrollX: true` as well, if not when you make the page narrower than the table the header won't align with the columns
___
*[`Ploutos/dashboard/templates/dashboard/bar_chart.html` line 68 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WVr8zD3hCn5jQD-h2:-N7WVr8zD3hCn5jQD-h3:b-iyvhz2) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/bar_chart.html#L68)):*
> ```HTML
>         columnDefs: [
>             { "width": "20%",
>             "targets": 0 
> ```

whitespace
___
*[`Ploutos/dashboard/templates/dashboard/base.html` line 18 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WWaYU7qU5d9LbIlZc:-N7WWaYU7qU5d9LbIlZd:b-58thti) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/base.html#L18)):*
> ```HTML
> 
> 
>     <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
> ```

can you move all the script tags to right before the closing body tags to speed up page loading and try group you stylesheets by type (i.e. datatables together)
___
*[`Ploutos/dashboard/templates/dashboard/files.html` line 6 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WWy1R4QQY-F54qgA6:-N7WWy1R4QQY-F54qgA7:bft4tjm) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/files.html#L6)):*
> ```HTML
> 
> <!-- Highlights current page and removes highlighting from previous -->
> <script>
> ```

scripts at bottom pls
___
*[`Ploutos/dashboard/templates/dashboard/files.html` line 21 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WX-eFDLAwHrrCI4hp:-N7WX-eFDLAwHrrCI4hq:bqd48id) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/files.html#L21)):*
> ```HTML
>     $(document).ready(function () {
>     $('.dataframe').DataTable( {
>         scrollY: '50vh',
> ```

scrollX again maybe probably
___
*[`Ploutos/dashboard/templates/dashboard/jobs.html` line 11 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WXI_h0At2vxiVR9k1:-N7WXI_h0At2vxiVR9k2:b-iyvhz2) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/jobs.html#L11)):*
> ```HTML
> <script>
>     var jobs = document.getElementById("jobs");
>     jobs.classList.add('active');                  
> ```

whitespace
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 548 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WY7K39aPP9b41gYMb:-N7WY7K39aPP9b41gYMc:bucxasi) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/DNAnexus_queries.py#L548)):*
> ```Python
>     how_many_unique_projects = list(file_df.project.unique())
>     projects_left_in_this_df = list(states_filled_in.project.unique())
>     empty_projs = [
> ```

using sets will be quicker:

```
list(set(how_many_unique_projects) - set(projects_left_in_this_df))
```
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 622 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WYUemDOYbA4C7yBxI:-N7WYUen4dY4DRbrKI3e:b5h7m18) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/DNAnexus_queries.py#L622)):*
> ```Python
>                             |
>                             ▼
>     +-----------+-------------------+---------------+--------------------+
> ```

does this docstring reflect the returned format now? (looks excellent btw)
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 862 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WYjGiEyVRL77aAeIC:-N7WYjGiEyVRL77aAeID:bvtul90) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/DNAnexus_queries.py#L862)):*
> ```Python
> 
> 
> def get_executions(proj):
> ```

is this robs code? should it be here to rev [...]

2022-07-22 09:33 UTC, rklocke reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/7)* status: 7 of 21 files reviewed, 16 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 62 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WR3DA825PkV82Wpbk:-N7Zvexk99x0URubRWp3:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/forms.py#L62)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

since you're not doing anything if start and end are true, this can be one line:
```
if start and not end:
```
</blockquote></details>

Done.
___
*[`Ploutos/dashboard/forms.py` line 69 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WRE4f0l-R_NsqW3aV:-N7ZvfQZCF6LkHOB3H3l:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/forms.py#L69)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`Ploutos/dashboard/forms.py` line 184 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WRfhuDtWj2UDZIKLY:-N7Wc8LE2vWNSXd1pDOL:bysdrpg) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/forms.py#L184)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

should these be in a config?
</blockquote></details>

Oops these form choices aren't used anymore since it's a free text box, have removed
___
*[`Ploutos/dashboard/models.py` line 75 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WSa-98DCpgcLOg_Ld:-N7_8x8-9WuFkmvegXMD:b1h65th) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/models.py#L75)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

are these commented out from being old ones of robs? can you delete them if so to reduce conflicts on the next PR
</blockquote></details>

Done, have changed models to the same state as development branch as per Rob's PR
___
*[`Ploutos/dashboard/views.py` line 68 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WTBnWD3lpkYBS68yS:-N7Zwpjx1ShMl6g2pC7Y:b-d0jidm) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/views.py#L68)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what are chat and chart2? could these be more descriptive? if not a comment on what each are in the context of this part of the code would be useful (i.e chart is blah and chart 2 is blah)
</blockquote></details>

Changed chart to daily_chart and chart2 to monthly_chart so easier to understand
___
*[`Ploutos/dashboard/templates/dashboard/bar_chart.html` line 5 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WVbCu2cR5g3eDp5ko:-N7_6QJV5twpucJz3UNY:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/bar_chart.html#L5)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can  you move all `<script>` tags to the bottom. this will speed up loading
</blockquote></details>

Done.
___
*[`Ploutos/dashboard/templates/dashboard/bar_chart.html` line 61 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WVxMC5ACGi2HBEIM-:-N7ZxaPG40WINDI_F2G2:b-1p7tyx) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/bar_chart.html#L61)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I think you want `scrollX: true` as well, if not when you make the page narrower than the table the header won't align with the columns
</blockquote></details>

This seemed to ruin the formatting of the table with a big bit of empty table space on the right, can I leave for now?
___
*[`Ploutos/dashboard/templates/dashboard/bar_chart.html` line 68 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WVr8zD3hCn5jQD-h2:-N7_-ejFDseZH71DINHO:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/bar_chart.html#L68)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

Done.
___
*[`Ploutos/dashboard/templates/dashboard/base.html` line 18 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WWaYU7qU5d9LbIlZc:-N7_6S2gE6WS20mf9d82:bx04b6p) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/base.html#L18)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you move all the script tags to right before the closing body tags to speed up page loading and try group you stylesheets by type (i.e. datatables together)
</blockquote></details>

I've grouped them and tried to move them to before the end of the closing body tags (in the same order as currently) but then no Highcharts show and the DataTables aren't interactive - any ideas?
___
*[`Ploutos/dashboard/templates/dashboard/files.html` line 6 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WWy1R4QQY-F54qgA6:-N7_6yZo4w56b_9nr4Ea:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/files.html#L6)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

scripts at bottom pls
</blockquote></details>

Done.
___
*[`Ploutos/dashboard/templates/dashboard/files.html` line 21 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WX-eFDLAwHrrCI4hp:-N7_7ugGAR3qpwpfKOlm:b-8ex3m7) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/files.html#L21)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

scrollX again maybe probably
</blockquote></details>

same issue as before
___
*[`Ploutos/dashboard/templates/dashboard/jobs.html` line 11 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WXI_h0At2vxiVR9k1:-N7_85Do8bGGpPH61dwc:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/jobs.html#L11)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 548 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WY7K39aPP9b41gYMb:-N7_9Uj23FE4wt1mLTZh:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/DNAnexus_queries.py#L548)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

using sets will be quicker:

```
list(set(how_many_unique_projects) - set(projects_left_in_this_df))
```
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 622 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WYUemDOYbA4C7yBxI:-N7_88KT3NlQgmXy0QB5:b-vwvf5z) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/DNAnexus_queries.py#L622)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this docstring reflect the returned format now? (looks excellent btw)
</blockquote></details>

Yes, this df is used for populating the db rather than displaying via a DataTable (the proj-level file type dfs shown on the File Type Storage page are generated each time the charts are changed by each size chart function in file_plots.py)
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 862 at r2](https://rev [...]

2022-07-22 11:49 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/7)* status: 7 of 21 files reviewed, 36 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

___
*[`Ploutos/scripts/file_plots.py` line 337 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_cssxA4OOerH67lTd:-N7_cssxA4OOerH67lTe:bmolkys) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L337)):*
if what you're wanting is to start at zero  and increment with by 2 you can still use enumerate instead of defining a counter:
```
>>> l
['a', 'b', 'c', 'd']
>>> for count, item in enumerate(l):
...     count = count * 2
...     print(count, item)
... 
0 a
2 b
4 c
6 d

```
___
*[`Ploutos/scripts/file_plots.py` line 421 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_dt3846SmWU4hyY9D:-N7_dt3846SmWU4hyY9E:b6qzyn3) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L421)):*
> ```Python
>         category_data_source = []
>         count = -1
>         for proj_type in proj_types:
> ```

this can just be `for count, proj_type in enumerate(proj_types):`
___
*[`Ploutos/scripts/file_plots.py` line 512 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_eICj9QcnCsLOqy78:-N7_eICj9QcnCsLOqy79:bnj7hl0) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L512)):*
> ```Python
>         category_data_source = []
>         count = -1
>         for proj_type in proj_types:
> ```

same as above
___
*[`Ploutos/scripts/file_plots.py` line 532 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_eNBEB4ti8fPTknin:-N7_eNBEB4ti8fPTknio:b1r92pk) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L532)):*
> ```Python
>                 'name': f"{proj_type}*",
>                 'data': [
>                     (entry.get('Live_Size')/1024)
> ```

pep8 will get enraged about not having spaces around numerical operators



_Code quote:_
```Python
/
```
___
*[`Ploutos/scripts/file_plots.py` line 532 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_er1d032S0QOcr0uH:-N7_er1d032S0QOcr0uI:b-yz9wc1) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L532)):*
> ```Python
>                 'name': f"{proj_type}*",
>                 'data': [
>                     (entry.get('Live_Size')/1024)
> ```

can you add a comment to say you're converting GiB -> TiB
___
*[`Ploutos/scripts/file_plots.py` line 544 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_e_BGDpNdoRUyXEJE:-N7_e_BGDpNdoRUyXEJF:bhsyiky) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L544)):*
> ```Python
>                 'name': f"{proj_type}*",
>                 'data': [
>                     (entry.get('Archived_Size')/1024)
> ```

here also



_Code quote:_
```Python
/
```
___
*[`Ploutos/scripts/file_plots.py` line 630 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_ecb49efgtRzM4iQD:-N7_ecb57ssQIH12vxO9:b-rufndm) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L630)):*
> ```Python
>         category_data_source = []
>         count = -1
>         for assay_type in assay_types:
> ```

rateenum
___
*[`Ploutos/scripts/file_plots.py` line 719 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_eyvfAx19JV8LKg2V:-N7_eyvgDNofDRh9fIDg:b-ru9ri4) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L719)):*
> ```Python
>         category_data_source = []
>         count = -1
>         for assay_type in assay_types:
> ```

ratenume
___
*[`Ploutos/scripts/populate_db.py` line 14 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_fCXL5DzlVljFokhZ:-N7_fCXMEQacn2CHGxdG:b-7hzgo0) ([raw file](https://github.com/eastgenomics/ploutos/blob/05efa117e8842e6ebc2e0cd305f980b1a5159703/Ploutos/scripts/populate_db.py#L14)):*
> ```Python
> from django.apps import apps
> from django.conf import settings
> from dashboard.models import (
> ```

if more get added it might make sense to just do `import dashboard.models as models`, not essential now as it will mean lots of changes, but a future  consideration
___
*[`Ploutos/scripts/populate_db.py` line 88 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_fZhnBDYiTm4jGvBh:-N7_fZhnBDYiTm4jGvBi:bb0utjd) ([raw file](https://github.com/eastgenomics/ploutos/blob/05efa117e8842e6ebc2e0cd305f980b1a5159703/Ploutos/scripts/populate_db.py#L88)):*
> ```Python
>     getting the date IDs or creating them first.
> 
>     Parameters
> ```

generally wouldn't worry about including empty params/returns, especially as you have None return type hint (which is excellent)
___
*[`Ploutos/scripts/populate_db.py` line 154 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_ftXI0G1ij76inxPV:-N7_ftXI0G1ij76inxPW:b-rtazri) ([raw file](https://github.com/eastgenomics/ploutos/blob/05efa117e8842e6ebc2e0cd305f980b1a5159703/Ploutos/scripts/populate_db.py#L154)):*
> ```Python
>     """
>     Puts the file type data into the db
>     ----------
> ```

Parameters
-----------------
___
*[`Ploutos/scripts/populate_db.py` line 191 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_gANfE0WS14Tu-dan:-N7_gANfE0WS14Tu-dao:b-8fgiqw) ([raw file](https://github.com/eastgenomics/ploutos/blob/05efa117e8842e6ebc2e0cd305f980b1a5159703/Ploutos/scripts/populate_db.py#L191)):*
> ```Python
> 
>         # Do same for BAMs
>         new_file_type, created = FileTypes.objects.get_or_create(
> ```

be careful reusing variables inside the same scope, if nothing was returned for some reason and a variable doesn't get overridden you could get wrongly variable values being used
___
*[`Ploutos/scripts/populate_db.py` line 237 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_gV52EWI69drxPK0S:-N7_gV52EWI69drxPK0T:b8yify1) ([raw file](https://github.com/eastgenomics/ploutos/blob/05efa117e8842e6ebc2e0cd305f980b1a5159703/Ploutos/scripts/populate_db.py#L237)):*
> ```Python
>     Parameters
>     ----------
>     all_executions_df:
> ```

missing type
___
*[`Ploutos/scripts/populate_db.py` line 283 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_gfbX2eshSM4QCMbT:-N7_gfbX2eshSM4QCMbU:bl2onwb) ([raw file](https://github.com/eastgenomics/ploutos/blob/05efa117e8842e6ebc2e0cd305f980b1a5159703/Ploutos/scripts/populate_db.py#L283)):*
> ```Python
>     """
>     start = time()
>     print(strftime("%Y-%m-%d %H:%M:%S", localtime()))
> ```

can this be logged instead/as well as printing?
___
*[`Ploutos/scripts/running_total_plots.py` line 164 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_hMv20x3rRUDSYECb:-N7_hMv20x3rRUDSYECc:bb7phvt) ([raw file](https://github.com/eastgenomics/ploutos/blob/05efa117e8842e6ebc2e0cd305f980b1a5159703/Ploutos/scripts/running_total_plots.py#L164)):*
> ```Python
>         """
>         # Filter between start of start_month
>         # And 1st of the montht hat comes after end_month
> ```

typo



_Code quote:_
```Python
montht hat
```
___
*[`Ploutos/scripts/running_total_plots.py` line 206 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_hbTE5x5k_dcUxIZY:-N7_hbTF7EEukFY_IT1-:b-say2gz) ([raw file](https://github.com/eastgenomics/ploutos/blob/05efa117e8842e6ebc2e0cd305f980b1a5159703/Ploutos/scripts/running_total_plots.py#L206)):*
> ```Python
>         # Instead take the last entry of the current month
>         # To act as the 1st of the next month in its place
>         if check_end_month not in key_list:
> ```

would this ever be empty list and raise  [...]

2022-07-22 11:56 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/7)* status: 7 of 21 files reviewed, 23 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

___
*[`Ploutos/dashboard/templates/dashboard/bar_chart.html` line 61 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WVxMC5ACGi2HBEIM-:-N7_jqxOAvaN90s6rGd5:blwjr6) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/bar_chart.html#L61)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

This seemed to ruin the formatting of the table with a big bit of empty table space on the right, can I leave for now?
</blockquote></details>

huh weird, sure thats fine
___
*[`Ploutos/dashboard/templates/dashboard/base.html` line 18 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WWaYU7qU5d9LbIlZc:-N7_jzAADjYQvLy-QM2Q:b-oveco2) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/base.html#L18)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

I've grouped them and tried to move them to before the end of the closing body tags (in the same order as currently) but then no Highcharts show and the DataTables aren't interactive - any ideas?
</blockquote></details>

huh maybe they need to be above the function calls (which would make sense), they're fine in the header then
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 548 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WY7K39aPP9b41gYMb:-N7_kOBA64sWA8RBRjuM:bgyo6kk) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/DNAnexus_queries.py#L548)):*
having a `list()` call inside `[]` wil; return a list in a list, do you want this?
```
>>> l1=[1,2,3,4]
>>> l2=[3,4,5,6]
>>> [list(set(l1) - set(l2))]
[[1, 2]]
>>> 

```


<!-- Sent from Reviewable.io -->

2022-07-22 13:58 UTC, rklocke reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/7)* status: 7 of 21 files reviewed, 22 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`Ploutos/dashboard/templates/dashboard/bar_chart.html` line 61 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WVxMC5ACGi2HBEIM-:-N7_rZkjBhGwdW8tkZTd:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/bar_chart.html#L61)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

huh weird, sure thats fine
</blockquote></details>

Done.
___
*[`Ploutos/dashboard/templates/dashboard/base.html` line 18 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WWaYU7qU5d9LbIlZc:-N7_r_S91aRPvsO_F-y-:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/dashboard/templates/dashboard/base.html#L18)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

huh maybe they need to be above the function calls (which would make sense), they're fine in the header then
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 548 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7WY7K39aPP9b41gYMb:-N7_ssWC5HZnZfG2SkbM:b-os2pb5) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/DNAnexus_queries.py#L548)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

having a `list()` call inside `[]` wil; return a list in a list, do you want this?
```
>>> l1=[1,2,3,4]
>>> l2=[3,4,5,6]
>>> [list(set(l1) - set(l2))]
[[1, 2]]
>>> 

```
</blockquote></details>

oops, updated
___
*[`Ploutos/scripts/file_plots.py` line 337 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_cssxA4OOerH67lTd:-N7_v_hK4Y-XJrYz7nH1:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L337)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

if what you're wanting is to start at zero  and increment with by 2 you can still use enumerate instead of defining a counter:
```
>>> l
['a', 'b', 'c', 'd']
>>> for count, item in enumerate(l):
...     count = count * 2
...     print(count, item)
... 
0 a
2 b
4 c
6 d

```
</blockquote></details>

Done.
___
*[`Ploutos/scripts/file_plots.py` line 421 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_dt3846SmWU4hyY9D:-N7_vsDmAH0_HlXklcQM:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L421)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this can just be `for count, proj_type in enumerate(proj_types):`
</blockquote></details>

Done.
___
*[`Ploutos/scripts/file_plots.py` line 512 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_eICj9QcnCsLOqy78:-N7_vsc54kqtx1l3B9KI:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L512)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`Ploutos/scripts/file_plots.py` line 532 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_eNBEB4ti8fPTknin:-N7_wJvi6ky9--Nay36Y:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L532)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

pep8 will get enraged about not having spaces around numerical operators
</blockquote></details>

Done.
___
*[`Ploutos/scripts/file_plots.py` line 532 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_er1d032S0QOcr0uH:-N7_wdff6VGRDHAhFFta:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L532)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you add a comment to say you're converting GiB -> TiB
</blockquote></details>

Done.
___
*[`Ploutos/scripts/file_plots.py` line 544 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_e_BGDpNdoRUyXEJE:-N7_wh4J0JKZA0ucYxTF:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L544)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

here also
</blockquote></details>

Done.
___
*[`Ploutos/scripts/file_plots.py` line 630 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_ecb49efgtRzM4iQD:-N7_witQ8xh9RrJ0T8E6:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L630)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

rateenum
</blockquote></details>

Done.
___
*[`Ploutos/scripts/file_plots.py` line 719 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_eyvfAx19JV8LKg2V:-N7_wj8e6JcFobTU6P54:b-8lga6x) ([raw file](https://github.com/eastgenomics/ploutos/blob/555f3010e6eb744b3bc970dc4c27d236ce652a53/Ploutos/scripts/file_plots.py#L719)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ratenume
</blockquote></details>

.enoD
___
*[`Ploutos/scripts/populate_db.py` line 14 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_fCXL5DzlVljFokhZ:-N7_wp7gBc8tS-OF3R7t:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/05efa117e8842e6ebc2e0cd305f980b1a5159703/Ploutos/scripts/populate_db.py#L14)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

if more get added it might make sense to just do `import dashboard.models as models`, not essential now as it will mean lots of changes, but a future  consideration
</blockquote></details>

Done.
___
*[`Ploutos/scripts/populate_db.py` line 88 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_fZhnBDYiTm4jGvBh:-N7_xYZT05o88ZOqn9c7:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/05efa117e8842e6ebc2e0cd305f980b1a5159703/Ploutos/scripts/populate_db.py#L88)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

generally wouldn't worry about including empty params/returns, especially as you have None return type hint (which is excellent)
</blockquote></details>

Done.
___
*[`Ploutos/scripts/populate_db.py` line 154 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_ftXI0G1ij76inxPV:-N7_xhKL1-9fjKd55UDB:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/05efa117e8842e6ebc2e0cd305f980b1a5159703/Ploutos/scripts/populate_db.py#L154)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Parameters
-----------------
</blockquote></details>

Done.
___
*[`Ploutos/scripts/populate_db.py` line 191 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_gANfE0WS14Tu-dan:-N7_yN4KA-cAACZ-p1l7:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/05efa117e8842e6ebc2e0cd305f980b1a5159703/Ploutos/scripts/populate_db.py#L191)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

be careful reusing variables inside the same scope, if nothing was returned for some reason and a variable doesn't get overridden you could get wrongly variable values being used
</blockquote></details>

Done.
___
*[`Ploutos/scripts/populate_db.py` line 237 at r4](https://reviewable.io/reviews/eastgenomics/ploutos/7#-N7_gV52EWI69drxPK0S:-N7_yfsj86niYSAdxiAH:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/05efa117e8842e6ebc2e0cd305f980b1a5159703/Ploutos/scripts/populate_db.py#L237)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blo [...]

2022-07-22 15:48 UTC, jethror1 reviewed
> Reviewed 4 of 12 files at r4, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/7)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1 and @RSWilson1)



<!-- Sent from Reviewable.io -->

2022-07-22 15:49 UTC, jethror1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RSWilson1)



<!-- Sent from Reviewable.io -->

2022-07-22 15:54 UTC, jethror1 approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RSWilson1)



<!-- Sent from Reviewable.io -->

2022-07-22 15:54 UTC, merged